In [1]:
import os
import numpy as np

## Validating the standard multiplicative shear bias

Valiation of the multiplicative shear bias which was already available on Firecrown.

$C^{i,j}_\ell \to (1+\Delta m)^2 C^{i,j}_\ell$

in this example, $\Delta m = 1.0$, so we expect, $C^{multi} / C^{null} = 4$

In [2]:
path_null = '/global/cscratch1/sd/davidsan/new_firecrown/firecrown/examples/hsc_3x2pt/cosmicshear/multiplicative_shear_bias_validation/cosmicshear-null-multi/data_vector/'
path_multi = '/global/cscratch1/sd/davidsan/new_firecrown/firecrown/examples/hsc_3x2pt/cosmicshear/multiplicative_shear_bias_validation/cosmicshear-multi1/data_vector/'

In [43]:
cl_null = np.loadtxt(os.path.join(path_null, 'theory_galaxy_shear_cl_ee_source_2_source_2.txt'))
cl_multi = np.loadtxt(os.path.join(path_multi, 'theory_galaxy_shear_cl_ee_source_2_source_2.txt'))

In [44]:
cl_null

array([3.78960382e-10, 2.25335583e-10, 1.42520944e-10, 1.02771961e-10,
       7.11857258e-11, 4.91870152e-11])

In [45]:
cl_multi

array([1.51584153e-09, 9.01342331e-10, 5.70083778e-10, 4.11087843e-10,
       2.84742903e-10, 1.96748061e-10])

In [46]:
ratio = cl_multi / cl_null

In [47]:
ratio

array([4., 4., 4., 4., 4., 4.])

# Validating our custom HSC multiplicative shear bias module

In [65]:
path_null_hsc = '/global/cscratch1/sd/davidsan/new_firecrown/firecrown/examples/hsc_3x2pt/cosmicshear/multiplicative_shear_bias_validation/cosmicshear-null-multi-hsc/data_vector/'

In [66]:
path_multi_hsc = '/global/cscratch1/sd/davidsan/new_firecrown/firecrown/examples/hsc_3x2pt/cosmicshear/multiplicative_shear_bias_validation/cosmicshear-multi100-multi-hsc/data_vector'

In [53]:
cl_null_hsc = np.loadtxt(os.path.join(path_null_hsc, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))

In [54]:
cl_null = np.loadtxt(os.path.join(path_null, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))

In [55]:
cl_null_hsc / cl_null

array([1.03423859, 1.03423859, 1.03423859, 1.03423859, 1.03423859,
       1.03423859])

# Test 2. Checking between module versions [$C_\ell$ with null $\Delta m = 0$ case]

In this case, the only difference between implementations:
    
* Standard multiplicative shear bias -> $C^{ij}_\ell \to (1 + \Delta m)^2 C^{ij}_\ell$
* HSC multiplicative shear bias -> $C^{ij}_\ell \to (1 + \Delta m)^2 (1 + m ^i_{sel} + m^i_R) (1 + m ^j_{sel} + m^j_R) C^{ij}_\ell$

In [50]:
cl_null_hsc

array([3.97446377e-10, 2.36327635e-10, 1.49473232e-10, 1.07785260e-10,
       7.46582232e-11, 5.15863976e-11])

In [51]:
cl_null_hsc / cl_null

array([1.04878081, 1.04878081, 1.04878081, 1.04878081, 1.04878081,
       1.04878081])

In [52]:
cl_null_hsc = np.loadtxt(os.path.join(path_null_hsc, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))

# Test 3. HSC Multipl. shear bias [Checkin auto-correlations.]

In [57]:
Delta_m = 1.0

In [58]:
for i in np.arange(4):
    print(f'Checking auto-correlation {i+1,i+1}')
    # Read Cls generated with HSC module and Delta m = 0
    cl_null_hsc = np.loadtxt(os.path.join(path_null_hsc, f'theory_galaxy_shear_cl_ee_source_{i}_source_{i}.txt'))
    
    # Read Cls generated with HSC module and Delta m = 100, equivalent to Delta m = 1.0 in the standard module
    cl_multi_hsc = np.loadtxt(os.path.join(path_multi_hsc, f'theory_galaxy_shear_cl_ee_source_{i}_source_{i}.txt'))
    
    ratio = cl_multi_hsc/cl_null_hsc
    
    factor = (1 + Delta_m) ** 2
    
    print(f'Are the input Delta m and the one applied to the Cl the same? {ratio == factor}')

Checking auto-correlation (1, 1)
Are the input Delta m and the one applied to the Cl the same? [ True  True  True  True  True  True]
Checking auto-correlation (2, 2)
Are the input Delta m and the one applied to the Cl the same? [ True  True  True  True  True  True]
Checking auto-correlation (3, 3)
Are the input Delta m and the one applied to the Cl the same? [ True  True  True  True  True  True]
Checking auto-correlation (4, 4)
Are the input Delta m and the one applied to the Cl the same? [ True  True  True  True  True  True]


In [116]:
cl_null = np.loadtxt(os.path.join(path_null, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))
cl_multi_hsc = np.loadtxt(os.path.join(path_multi_hsc, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))

In [117]:
cl_multi_hsc / cl_null

array([4.13695436, 4.13695436, 4.13695436, 4.13695436, 4.13695436,
       4.13695436])

In [118]:
(1 + 1) ** 2 * (1 + 0.91/100 + 1.5/100) * (1 + 0.99/100) 

4.13695436

# Test HSC multipl. shear bias [cross-correlations]
 
Checking that $(1 + m^i_{sel} + m^i_{R}) * (1 + m^j_{sel} + m^j_{R})$ are implemented correctly. To do so we check the ratio

Standard module -> $C^{i,j}_\ell \to (1+\Delta m)^2 C^{i,j}_\ell$ 

HSC module -> $C^{i,j}_\ell \to (1+\Delta m)^2 (1 + m^i_{sel} + m^i_{R}) * (1 + m^j_{sel} + m^j_{R}) C^{i,j}_\ell$

So the prediction of both modules must differ in $(1 + m^i_{sel} + m^i_{R}) * (1 + m^j_{sel} + m^j_{R})$

In [129]:
for i in np.arange(4):
    for j in np.arange(i, 4):
        
        print(f'Checking correlation {j+1,i+1}')
        cl_multi = np.loadtxt(os.path.join(path_multi, f'theory_galaxy_shear_cl_ee_source_{j}_source_{i}.txt'))
        cl_multi_hsc = np.loadtxt(os.path.join(path_multi_hsc, f'theory_galaxy_shear_cl_ee_source_{j}_source_{i}.txt'))
        
        if i==0:
            m_sel = 0.86/100
            m_R = 0.0
            factor_i = (1 + m_sel + m_R)
            
        elif i==1:
            m_sel = 0.99/100
            m_R = 0.0
            factor_i = (1 + m_sel + m_R)
            
        elif i==2:
            m_sel = 0.91/100
            m_R = 1.5/100
            factor_i = (1 + m_sel + m_R)
            
        elif i==3:
            m_sel = 0.91/100
            m_R = 3.0/100
            factor_i = (1 + m_sel + m_R)
            
        if j==0:
            m_sel = 0.86/100
            m_R = 0.0
            factor_j = (1 + m_sel + m_R)
            
        elif j==1:
            m_sel = 0.99/100
            m_R = 0.0
            factor_j = (1 + m_sel + m_R)
            
        elif j==2:
            m_sel = 0.91/100
            m_R = 1.5/100
            factor_j = (1 + m_sel + m_R)
            
        elif j==3:
            m_sel = 0.91/100
            m_R = 3.0/100
            factor_j = (1 + m_sel + m_R)
            
        ratio = cl_multi_hsc / cl_multi
        factor = factor_i * factor_j
        
        #print(ratio)
        #print(factor)
        
        print(f'is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? {ratio==factor}')

Checking correlation (1, 1)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (2, 1)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (3, 1)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (4, 1)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (2, 2)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (3, 2)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (4, 2)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (3, 3)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recovered? [ True  True  True  True  True  True]
Checking correlation (4, 3)
is the (1+msel^i+mR^i)*(1+msel^j+mR^j) recov

In [119]:
cl_multi = np.loadtxt(os.path.join(path_multi, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))
cl_multi_hsc = np.loadtxt(os.path.join(path_multi_hsc, 'theory_galaxy_shear_cl_ee_source_2_source_1.txt'))

In [120]:
cl_multi_hsc / cl_multi

array([1.03423859, 1.03423859, 1.03423859, 1.03423859, 1.03423859,
       1.03423859])

In [121]:
(1 + 0.91/100 + 1.5/100) * (1 + 0.99/100) 

1.03423859